### PR TITLE
Update class-factory.blade.php view

### PR DESCRIPTION
**Pull request by alibori**
Hello!

I have modified the class factory view to include some configurations on it.

Thanks!

### CODE REVIEW

**Comment by TheDoctor0** [comment]
Hello @alibori.
First and foremost thank you for this contribution!

I do think that the additional content of the test factories is highly opinionated and I'm quite hesitant to include it.
Do you think that it would be useful to allow [customizing the default class stub like instead](https://laravel.com/docs/10.x/artisan#stub-customization)?

**Comment by alibori** [comment]
Hello @TheDoctor0 !

Yes, I think it would be useful :)

Thanks for your response!

**Comment by TheDoctor0** [comment]
@alibori I just tagged a 1.3.0 release that includes a [customizable factory template](https://github.com/TheDoctor0/laravel-factory-generator#customizing-the-factory-template).

**Comment by alibori** [comment]
Hello @TheDoctor0 !

Perfect, that's great.

Thanks a lot!

**Pull request closed without merging**
